/* Use Value Attribute with Radio Buttons and Checkboxes

When a form is submitted, the data is sent to the server and includes entries for
    options selected.
Inputs of the radio and checkbox report their values from the value attribute.
When a form is submited, the form data will include the name and the value attribute of
    the option selected.
Default value attribute is set to on, which isn't very helpfule, so the value attribute
    needs to be set to something to identify the option.

*/

/*Check Radio Button and Checkboxes by Default

Checkboxes and radio buttons can be checked by default by using the checked attribute.
Just add the "checked" to the inside of an input element.

Need to learn how to set them in react.
Can only Check one radio button or checkmark with the checked attribute?

*/

/*Nest Many Elements within a Single Div Element

The div element, which is also known as the division element, is a general purpose
    container for other elements.

*/

/*Declare the DOCTYPE of an html Document

Give structure to an html document
<DOCTYPE html>
<html></html>
 */


/*Define the Head and Body of an HTML Document

Used to add more organization to an html document
Any markup with information about the page would go in the head tag.
Any markup with the content of the page goes in the body tag.
Metadata elements, such as link, meta, title, and style, goes in the head tag.
*/

CSS

/* Change the Color of Text

We can change the color of text by changing the style of our element.
The property that is responsible for the color of an element text is the
    color style property.
example: <h2 style=" color: red;">Born to Be Wild</h2>
It is good practice to end a style declaration with a semicolon.

*/